(cl:defpackage arlo_auto_docking-msg
  (:use )
  (:export
   "<AUTODOCKACTION>"
   "AUTODOCKACTION"
   "<AUTODOCKACTIONFEEDBACK>"
   "AUTODOCKACTIONFEEDBACK"
   "<AUTODOCKACTIONGOAL>"
   "AUTODOCKACTIONGOAL"
   "<AUTODOCKACTIONRESULT>"
   "AUTODOCKACTIONRESULT"
   "<AUTODOCKFEEDBACK>"
   "AUTODOCKFEEDBACK"
   "<AUTODOCKGOAL>"
   "AUTODOCKGOAL"
   "<AUTODOCKRESULT>"
   "AUTODOCKRESULT"
  ))

