; Auto-generated. Do not edit!


(cl:in-package arlo_auto_docking-msg)


;//! \htmlinclude AutoDockGoal.msg.html

(cl:defclass <AutoDockGoal> (roslisp-msg-protocol:ros-message)
  ((request
    :reader request
    :initarg :request
    :type cl:string
    :initform ""))
)

(cl:defclass AutoDockGoal (<AutoDockGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AutoDockGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AutoDockGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arlo_auto_docking-msg:<AutoDockGoal> is deprecated: use arlo_auto_docking-msg:AutoDockGoal instead.")))

(cl:ensure-generic-function 'request-val :lambda-list '(m))
(cl:defmethod request-val ((m <AutoDockGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arlo_auto_docking-msg:request-val is deprecated.  Use arlo_auto_docking-msg:request instead.")
  (request m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AutoDockGoal>) ostream)
  "Serializes a message object of type '<AutoDockGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'request))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'request))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AutoDockGoal>) istream)
  "Deserializes a message object of type '<AutoDockGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'request) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'request) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AutoDockGoal>)))
  "Returns string type for a message object of type '<AutoDockGoal>"
  "arlo_auto_docking/AutoDockGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AutoDockGoal)))
  "Returns string type for a message object of type 'AutoDockGoal"
  "arlo_auto_docking/AutoDockGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AutoDockGoal>)))
  "Returns md5sum for a message object of type '<AutoDockGoal>"
  "9b13f31f7a0a36901919f7ec0d9f40d4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AutoDockGoal)))
  "Returns md5sum for a message object of type 'AutoDockGoal"
  "9b13f31f7a0a36901919f7ec0d9f40d4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AutoDockGoal>)))
  "Returns full string definition for message of type '<AutoDockGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%string request~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AutoDockGoal)))
  "Returns full string definition for message of type 'AutoDockGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal         ~%string request~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AutoDockGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'request))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AutoDockGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AutoDockGoal
    (cl:cons ':request (request msg))
))
