; Auto-generated. Do not edit!


(cl:in-package arlo_auto_docking-msg)


;//! \htmlinclude AutoDockResult.msg.html

(cl:defclass <AutoDockResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass AutoDockResult (<AutoDockResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AutoDockResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AutoDockResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arlo_auto_docking-msg:<AutoDockResult> is deprecated: use arlo_auto_docking-msg:AutoDockResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <AutoDockResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arlo_auto_docking-msg:result-val is deprecated.  Use arlo_auto_docking-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AutoDockResult>) ostream)
  "Serializes a message object of type '<AutoDockResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AutoDockResult>) istream)
  "Deserializes a message object of type '<AutoDockResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AutoDockResult>)))
  "Returns string type for a message object of type '<AutoDockResult>"
  "arlo_auto_docking/AutoDockResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AutoDockResult)))
  "Returns string type for a message object of type 'AutoDockResult"
  "arlo_auto_docking/AutoDockResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AutoDockResult>)))
  "Returns md5sum for a message object of type '<AutoDockResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AutoDockResult)))
  "Returns md5sum for a message object of type 'AutoDockResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AutoDockResult>)))
  "Returns full string definition for message of type '<AutoDockResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AutoDockResult)))
  "Returns full string definition for message of type 'AutoDockResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AutoDockResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AutoDockResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AutoDockResult
    (cl:cons ':result (result msg))
))
