// Generated by gencpp from file smf_move_base_msgs/Goto2DFeedback.msg
// DO NOT EDIT!


#ifndef SMF_MOVE_BASE_MSGS_MESSAGE_GOTO2DFEEDBACK_H
#define SMF_MOVE_BASE_MSGS_MESSAGE_GOTO2DFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smf_move_base_msgs
{
template <class ContainerAllocator>
struct Goto2DFeedback_
{
  typedef Goto2DFeedback_<ContainerAllocator> Type;

  Goto2DFeedback_()
    {
    }
  Goto2DFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct Goto2DFeedback_

typedef ::smf_move_base_msgs::Goto2DFeedback_<std::allocator<void> > Goto2DFeedback;

typedef boost::shared_ptr< ::smf_move_base_msgs::Goto2DFeedback > Goto2DFeedbackPtr;
typedef boost::shared_ptr< ::smf_move_base_msgs::Goto2DFeedback const> Goto2DFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace smf_move_base_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smf_move_base_msgs/Goto2DFeedback";
  }

  static const char* value(const ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
;
  }

  static const char* value(const ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goto2DFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::smf_move_base_msgs::Goto2DFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SMF_MOVE_BASE_MSGS_MESSAGE_GOTO2DFEEDBACK_H
