// Generated by gencpp from file smf_move_base_msgs/RelevantAgentState.msg
// DO NOT EDIT!


#ifndef SMF_MOVE_BASE_MSGS_MESSAGE_RELEVANTAGENTSTATE_H
#define SMF_MOVE_BASE_MSGS_MESSAGE_RELEVANTAGENTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pedsim_msgs/AgentState.h>

namespace smf_move_base_msgs
{
template <class ContainerAllocator>
struct RelevantAgentState_
{
  typedef RelevantAgentState_<ContainerAllocator> Type;

  RelevantAgentState_()
    : header()
    , agent_state()
    , relevance(0)
    , last_time(0)  {
    }
  RelevantAgentState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , agent_state(_alloc)
    , relevance(0)
    , last_time(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::pedsim_msgs::AgentState_<ContainerAllocator>  _agent_state_type;
  _agent_state_type agent_state;

   typedef int8_t _relevance_type;
  _relevance_type relevance;

   typedef uint64_t _last_time_type;
  _last_time_type last_time;





  typedef boost::shared_ptr< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> const> ConstPtr;

}; // struct RelevantAgentState_

typedef ::smf_move_base_msgs::RelevantAgentState_<std::allocator<void> > RelevantAgentState;

typedef boost::shared_ptr< ::smf_move_base_msgs::RelevantAgentState > RelevantAgentStatePtr;
typedef boost::shared_ptr< ::smf_move_base_msgs::RelevantAgentState const> RelevantAgentStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator1> & lhs, const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.agent_state == rhs.agent_state &&
    lhs.relevance == rhs.relevance &&
    lhs.last_time == rhs.last_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator1> & lhs, const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smf_move_base_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334a2c2f98b7c74d4ac85f426a0f481e";
  }

  static const char* value(const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334a2c2f98b7c74dULL;
  static const uint64_t static_value2 = 0x4ac85f426a0f481eULL;
};

template<class ContainerAllocator>
struct DataType< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smf_move_base_msgs/RelevantAgentState";
  }

  static const char* value(const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"pedsim_msgs/AgentState agent_state\n"
"int8 relevance\n"
"uint64 last_time\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: pedsim_msgs/AgentState\n"
"Header header\n"
"uint64 id\n"
"uint16 type\n"
"string social_state\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Twist twist\n"
"pedsim_msgs/AgentForce forces\n"
"\n"
"# Use sensors package to control observability\n"
"\n"
"# Social State string constants\n"
"string      TYPE_STANDING = \"standing\"\n"
"string      TYPE_INDIVIDUAL_MOVING = \"individual_moving\"\n"
"string      TYPE_WAITING_IN_QUEUE = \"waiting_in_queue\"\n"
"string      TYPE_GROUP_MOVING = \"group_moving\"\n"
"string      TYPE_FROZEN = \"frozen\"\n"
"\n"
"# Agent types\n"
"# 0, 1 -> ordinary agents\n"
"# 2 -> Robot\n"
"# 3 -> standing/elderly agents\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: pedsim_msgs/AgentForce\n"
"# Forces acting on an agent.\n"
"\n"
"# Basic SFM forces.\n"
"geometry_msgs/Vector3 desired_force\n"
"geometry_msgs/Vector3 obstacle_force\n"
"geometry_msgs/Vector3 social_force\n"
"\n"
"# Additional Group Forces\n"
"geometry_msgs/Vector3 group_coherence_force\n"
"geometry_msgs/Vector3 group_gaze_force\n"
"geometry_msgs/Vector3 group_repulsion_force\n"
"\n"
"# Extra stabilization/custom forces.\n"
"geometry_msgs/Vector3 random_force\n"
;
  }

  static const char* value(const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.agent_state);
      stream.next(m.relevance);
      stream.next(m.last_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelevantAgentState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smf_move_base_msgs::RelevantAgentState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "agent_state: ";
    s << std::endl;
    Printer< ::pedsim_msgs::AgentState_<ContainerAllocator> >::stream(s, indent + "  ", v.agent_state);
    s << indent << "relevance: ";
    Printer<int8_t>::stream(s, indent + "  ", v.relevance);
    s << indent << "last_time: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.last_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMF_MOVE_BASE_MSGS_MESSAGE_RELEVANTAGENTSTATE_H
