// Generated by gencpp from file arlo_auto_docking/AutoDockFeedback.msg
// DO NOT EDIT!


#ifndef ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKFEEDBACK_H
#define ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arlo_auto_docking
{
template <class ContainerAllocator>
struct AutoDockFeedback_
{
  typedef AutoDockFeedback_<ContainerAllocator> Type;

  AutoDockFeedback_()
    : feedback()  {
    }
  AutoDockFeedback_(const ContainerAllocator& _alloc)
    : feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockFeedback_

typedef ::arlo_auto_docking::AutoDockFeedback_<std::allocator<void> > AutoDockFeedback;

typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockFeedback > AutoDockFeedbackPtr;
typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockFeedback const> AutoDockFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arlo_auto_docking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arlo_auto_docking/AutoDockFeedback";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"string feedback\n"
;
  }

  static const char* value(const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arlo_auto_docking::AutoDockFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKFEEDBACK_H
