// Generated by gencpp from file arlo_auto_docking/AutoDockResult.msg
// DO NOT EDIT!


#ifndef ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKRESULT_H
#define ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arlo_auto_docking
{
template <class ContainerAllocator>
struct AutoDockResult_
{
  typedef AutoDockResult_<ContainerAllocator> Type;

  AutoDockResult_()
    : result(false)  {
    }
  AutoDockResult_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockResult_

typedef ::arlo_auto_docking::AutoDockResult_<std::allocator<void> > AutoDockResult;

typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockResult > AutoDockResultPtr;
typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockResult const> AutoDockResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arlo_auto_docking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arlo_auto_docking/AutoDockResult";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"bool result\n"
;
  }

  static const char* value(const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arlo_auto_docking::AutoDockResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arlo_auto_docking::AutoDockResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKRESULT_H
