// Generated by gencpp from file arlo_auto_docking/AutoDockGoal.msg
// DO NOT EDIT!


#ifndef ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKGOAL_H
#define ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arlo_auto_docking
{
template <class ContainerAllocator>
struct AutoDockGoal_
{
  typedef AutoDockGoal_<ContainerAllocator> Type;

  AutoDockGoal_()
    : request()  {
    }
  AutoDockGoal_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> const> ConstPtr;

}; // struct AutoDockGoal_

typedef ::arlo_auto_docking::AutoDockGoal_<std::allocator<void> > AutoDockGoal;

typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockGoal > AutoDockGoalPtr;
typedef boost::shared_ptr< ::arlo_auto_docking::AutoDockGoal const> AutoDockGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator1> & lhs, const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arlo_auto_docking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arlo_auto_docking/AutoDockGoal";
  }

  static const char* value(const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal         \n"
"string request\n"
;
  }

  static const char* value(const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AutoDockGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arlo_auto_docking::AutoDockGoal_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARLO_AUTO_DOCKING_MESSAGE_AUTODOCKGOAL_H
