// Generated by gencpp from file esc_move_base_msgs/GotoRegion2DFeedback.msg
// DO NOT EDIT!


#ifndef ESC_MOVE_BASE_MSGS_MESSAGE_GOTOREGION2DFEEDBACK_H
#define ESC_MOVE_BASE_MSGS_MESSAGE_GOTOREGION2DFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esc_move_base_msgs
{
template <class ContainerAllocator>
struct GotoRegion2DFeedback_
{
  typedef GotoRegion2DFeedback_<ContainerAllocator> Type;

  GotoRegion2DFeedback_()
    {
    }
  GotoRegion2DFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GotoRegion2DFeedback_

typedef ::esc_move_base_msgs::GotoRegion2DFeedback_<std::allocator<void> > GotoRegion2DFeedback;

typedef boost::shared_ptr< ::esc_move_base_msgs::GotoRegion2DFeedback > GotoRegion2DFeedbackPtr;
typedef boost::shared_ptr< ::esc_move_base_msgs::GotoRegion2DFeedback const> GotoRegion2DFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace esc_move_base_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esc_move_base_msgs/GotoRegion2DFeedback";
  }

  static const char* value(const ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
;
  }

  static const char* value(const ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GotoRegion2DFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::esc_move_base_msgs::GotoRegion2DFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ESC_MOVE_BASE_MSGS_MESSAGE_GOTOREGION2DFEEDBACK_H
