// Generated by gencpp from file esc_move_base_msgs/Goto2DResult.msg
// DO NOT EDIT!


#ifndef ESC_MOVE_BASE_MSGS_MESSAGE_GOTO2DRESULT_H
#define ESC_MOVE_BASE_MSGS_MESSAGE_GOTO2DRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace esc_move_base_msgs
{
template <class ContainerAllocator>
struct Goto2DResult_
{
  typedef Goto2DResult_<ContainerAllocator> Type;

  Goto2DResult_()
    : success(false)  {
    }
  Goto2DResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> const> ConstPtr;

}; // struct Goto2DResult_

typedef ::esc_move_base_msgs::Goto2DResult_<std::allocator<void> > Goto2DResult;

typedef boost::shared_ptr< ::esc_move_base_msgs::Goto2DResult > Goto2DResultPtr;
typedef boost::shared_ptr< ::esc_move_base_msgs::Goto2DResult const> Goto2DResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator1> & lhs, const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator1> & lhs, const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace esc_move_base_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "esc_move_base_msgs/Goto2DResult";
  }

  static const char* value(const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool success\n"
;
  }

  static const char* value(const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Goto2DResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::esc_move_base_msgs::Goto2DResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESC_MOVE_BASE_MSGS_MESSAGE_GOTO2DRESULT_H
