; Auto-generated. Do not edit!


(cl:in-package esc_move_base_msgs-msg)


;//! \htmlinclude Goto2DFeedback.msg.html

(cl:defclass <Goto2DFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Goto2DFeedback (<Goto2DFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Goto2DFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Goto2DFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name esc_move_base_msgs-msg:<Goto2DFeedback> is deprecated: use esc_move_base_msgs-msg:Goto2DFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Goto2DFeedback>) ostream)
  "Serializes a message object of type '<Goto2DFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Goto2DFeedback>) istream)
  "Deserializes a message object of type '<Goto2DFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Goto2DFeedback>)))
  "Returns string type for a message object of type '<Goto2DFeedback>"
  "esc_move_base_msgs/Goto2DFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Goto2DFeedback)))
  "Returns string type for a message object of type 'Goto2DFeedback"
  "esc_move_base_msgs/Goto2DFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Goto2DFeedback>)))
  "Returns md5sum for a message object of type '<Goto2DFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Goto2DFeedback)))
  "Returns md5sum for a message object of type 'Goto2DFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Goto2DFeedback>)))
  "Returns full string definition for message of type '<Goto2DFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Goto2DFeedback)))
  "Returns full string definition for message of type 'Goto2DFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Goto2DFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Goto2DFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Goto2DFeedback
))
